config {
    type: "table",
    schema: "injenia",
    name: "F_FIFO"
}

SELECT * EXCEPT (action, rk)
FROM (
	SELECT
		*,
		ROW_NUMBER() OVER(
			PARTITION BY cod_franchising, barcode_negozio, tipo_ordine_cliente, origine_ordine, data_carico, data_scarico, tipo_scarico
			ORDER BY upd_datetime DESC
		) AS rk
	FROM ${ref("S_FIFO")}
	WHERE data_carico IN ({where_partitions_current_table})
)
WHERE rk = 1
AND action != 'DELETE'
		