config {
    type: "table",
    schema: "injenia",
    name: "F_TSL"
}
SELECT 
	fk_prodotto, id_negozio, qta, pregresso
FROM ${ref("DM_SELLOUT_STAGING", "{from_table}")} AS S_TSL
WHERE 
	_partitiontime IN ({partitions})
AND (id_negozio, upd_datetime) IN (
	SELECT AS STRUCT id_negozio, MAX(upd_datetime) AS upd_datetime
	FROM ${ref("DM_SELLOUT_STAGING", "{from_table}")} AS S_TSL
	WHERE _partitiontime IN ({partitions})
	GROUP BY id_negozio
)