config {
    type: "view",
    schema: "injenia",
    name: "d_iniziativa_input_output_partitions"
}

SELECT DISTINCT CAST((FLOOR((id_iniziativa - 1) / 100) * 100) as INT64) + 1
FROM (
	SELECT DISTINCT CAST(SPLIT(id, ":::")[OFFSET(0)] AS INT64) AS id_iniziativa
	FROM ${ref("S_LOG_INIZIATIVA_NEGOZIO")}
	WHERE _PARTITIONDATE = CURRENT_DATE

	UNION DISTINCT

	SELECT DISTINCT CAST(id AS INT64)
	FROM ${ref("S_LOG_INIZIATIVA")}
	WHERE _PARTITIONDATE = CURRENT_DATE
)
		