config {
    type: "table",
    schema: "injenia",
    name: "D_TIPO_TAGLIA_NAZIONE"
}

SELECT * EXCEPT (action, rk)
FROM (
	SELECT
		id,
		nazione_mmfg as nazione,
		attributes.* EXCEPT (nazione),
		timestamp AS ts_inserimento,
		RANK() OVER(PARTITION BY id ORDER BY timestamp DESC, GENERATE_UUID()) AS rk
	FROM ${ref("S_TIPO_TAGLIA_NAZIONE")} s
	JOIN ${ref("D_NAZIONE")} n ON (attributes.nazione_iso=nazione_iso)
)
WHERE rk = 1
AND action != 'DELETE'
		