config {
    type: "view",
    schema: "injenia",
    name: "ga_kpi_prodotto_basic_input_output_partitions"
}

SELECT DISTINCT PARSE_DATE('%Y%m%d', event_date)
FROM `mmfg-analytics-gruppo-prod.analytics_260123046.events_*`
WHERE _TABLE_SUFFIX = (SELECT * FROM ${ref("ga_kpi_prodotto_basic_get_last_shard")})
AND PARSE_DATE('%Y%m%d', event_date) NOT IN (
	SELECT event_date
	FROM `DM_DIGITAL.F_GA_KPI_PRODOTTO_BASIC_*`
)
		