config {
    type: "table",
    schema: "injenia",
    name: "F_DISPONIBILITA_202301011"
}

SELECT
	sku,
	warehouse,
	brand,
	quantity,
	date
FROM `mmfg-dwh-gruppo-prod.DM_DIGITAL_STAGING.S_DISPONIBILITA_*`
WHERE date IN (SELECT * FROM ${ref("f_disponibilita_input_output_partitions")})
QUALIFY ROW_NUMBER() OVER(PARTITION BY sku, warehouse, brand, date ORDER BY CASE source WHEN 'om' THEN 1 WHEN 'bms' THEN 2 ELSE 3 END ASC, ts_inserimento DESC) = 1
		