config {
    type: "view",
    schema: "injenia",
    name: "f_ga_intrend_app_input_output_partitions"
}
SELECT DISTINCT PARSE_DATE('%Y%m%d', event_date) as event_date
            FROM ${ref("analytics_248931566", "events_*")}
            where _TABLE_SUFFIX IN (
                    ifnull( ({partitions}), GREATEST("20220401", format_date('%Y%m%d', date_add(current_date, interval -1 day))))
                )