config {
    type: "incremental",
    schema: "injenia",
    name: "S_LOG_SPEDIZIONE_DELETE"
}

SELECT
	id,
	attributes.numero_bolla AS numero_bolla,
	attributes.serie_bolla AS serie_bolla,
	attributes.societa AS societa,
	_PARTITIONTIME AS ts_creazione,
	_PARTITIONDATE AS data_creazione
FROM `mmfg-dwh-gruppo-prod.DM_SELLOUT_STAGING.S_LOG_SPEDIZIONE`
WHERE attributes.action = 'DELETE'
AND _PARTITIONDATE IN (SELECT * FROM ${ref("s_log_sped_delete_input_output_partitions")})
		