config {
    type: "table",
    name: "D_CLIENTELA_CLUSTER"
}

SELECT * EXCEPT (action)
FROM (
	SELECT
		id,
		attributes.* EXCEPT(tipo_ordine_cliente),
		IFNULL(attributes.tipo_ordine_cliente, 'CV') AS tipo_ordine_cliente,
		timestamp AS ts_inserimento,
	FROM ${ref("DM_SELLOUT_STAGING", "S_CLIENTELA_CLUSTER")}
	WHERE True 
	QUALIFY ROW_NUMBER() OVER(PARTITION BY societa, anno, stagione, uscita_collezione, cliente, tipo_ordine_cliente ORDER BY timestamp DESC) = 1
)
WHERE action != 'DELETE' 
		