config {
    type: "view",
    schema: "injenia",
    name: "f_contabilita_congelata_input_partitions"
}

SELECT DISTINCT creation_date AS data_creazione,
FROM ${ref("MOV_MODIFIED_DATE")}
WHERE DATE(ts_lancio) >= CURRENT_DATE() - 1
	AND record_type IN ('BMS')
	AND EXTRACT(YEAR FROM creation_date) BETWEEN GREATEST(2021, EXTRACT(YEAR FROM CURRENT_DATE) - 5) and EXTRACT(YEAR FROM CURRENT_DATE) - 1
		