config {
    type: "view",
    schema: "DM_BMS",
    name: "f_contabilita_congelata_output_partitions"
}

SELECT DISTINCT DATE(ts_modifica) as data_modifica, AS value
FROM ${ref("DM_SELLOUT_STAGING", "S_MOVIMENTAZIONE_2*")}
WHERE data_creazione IN (SELECT * FROM ${ref("f_contabilita_congelata_input_partitions")})
	AND DATE(orario_evento) >= CURRENT_DATE() - 1
	AND record_type IN ('BMS')
	AND project_name IN ("maxima20","bmsde","mmltd")
		